<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_webform_submission_form_alter().
**/
function webform_submission_event_webform_submission_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  $form['#validate'][] = 'webform_submission_event_webform_submission_validate';
  $form['#attached']['library'][] = 'webform_submission_event/webform_submission_command';

  $form['valid_form'] = [
    '#type' => 'hidden',
  ];
}

function webform_submission_event_webform_submission_validate($form, FormStateInterface &$form_state){
  $errors = $form_state->getErrors();
  $valid_form = false;
  if (empty($errors)) {
    $valid_form = true;
  }

  $_REQUEST['valid_form'] = $valid_form;
}