definitions:
  standard__front_page:
    menu_name: top-menu
    parent: ''
    weight: -49
    expanded: false
    enabled: true
_core:
  default_config_hash: jdY7AU0tU-QsjmiOw3W8vwpYMb-By--_MSFgbqKUTYM
