module:
  address: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  backup_migrate: 0
  better_exposed_filters: 0
  block: 0
  block_class: 0
  block_content: 0
  bootstrap_paragraphs: 0
  breakpoint: 0
  captcha: 0
  ckeditor: 0
  color: 0
  comment: 0
  commerce: 0
  commerce_cart: 0
  commerce_order: 0
  commerce_price: 0
  commerce_product: 0
  commerce_quick_edit: 0
  commerce_store: 0
  config: 0
  contextual: 0
  crop: 0
  ctools: 0
  datetime: 0
  dblog: 0
  devel: 0
  draggableviews: 0
  dynamic_page_cache: 0
  editor: 0
  entity: 0
  entity_browser: 0
  entity_reference_revisions: 0
  exclude_node_title: 0
  field: 0
  field_formatter_class: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  focal_point: 0
  help: 0
  history: 0
  image: 0
  image_captcha: 0
  inline_entity_form: 0
  instawidget: 0
  kint: 0
  link: 0
  link_attributes: 0
  linkit: 0
  login_destination: 0
  media: 0
  media_entity_browser: 0
  menu_block: 0
  menu_item_extras: 0
  menu_link_attributes: 0
  menu_ui: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  profile: 0
  quickedit: 0
  rdf: 0
  recaptcha: 0
  responsive_image: 0
  search: 0
  shortcut: 0
  simple_sitemap: 0
  sitemap: 0
  state_machine: 0
  svg_image: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  trilliumlincoln_map: 0
  trilliumlincoln_sync: 0
  trilliumlincoln_utility: 0
  update: 0
  user: 0
  views_ajax_history: 0
  views_fieldsets: 0
  views_ui: 0
  viewsreference: 0
  webform: 0
  webform_submission_event: 0
  webform_ui: 0
  menu_link_content: 1
  pathauto: 1
  views: 10
  paragraphs: 11
  linked_field: 100
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  bootstrap: 0
  trilliumlincoln: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
