page_title: Sitemap
message:
  value: ''
  format: restricted_html
show_front: true
show_titles: true
show_books: {  }
books_expanded: true
show_menus:
  footer: footer
  main: main
  account: '0'
  admin: '0'
  devel: '0'
  tools: '0'
show_menus_hidden: false
show_vocabularies:
  tags: '0'
show_description: true
show_count: true
vocabulary_depth: -1
term_threshold: 0
forum_threshold: -1
rss_front: rss.xml
show_rss_links: 0
rss_taxonomy: -1
css: true
order:
  menus_admin: -50
  front: -49
  menus_account: -48
  menus_devel: -47
  menus_main: -46
  menus_footer: -45
  vocabularies_tags: -44
  menus_tools: -43
_core:
  default_config_hash: yUNkiSB-fp4pyUb6B2L9HiiCdISBDvK7r1v9_XkGUaQ
