schemas:
  bootstrap: 8000
  trilliumlincoln: 8000
favicon:
  mimetype: image/vnd.microsoft.icon
  path: themes/trilliumlincoln/favicon.ico
  url: 'http://drupal8.test/trilliumlincoln/themes/trilliumlincoln/favicon.ico'
  use_default: true
logo:
  path: 'public://logo.png'
  url: ''
  use_default: false
region_wells:
  header: ''
  navigation_top: ''
  navigation: ''
  navigation_collapsible: ''
  highlighted: ''
  help: ''
  content_top: ''
  content: ''
  content_bottom: ''
  footer: ''
  footer_bottom: ''
table_responsive: '-1'
table: ''
fluid_container: 1
forms_smart_descriptions: 0
breadcrumb_home: 1
breadcrumb_title: 0
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
modal_jquery_ui_bridge: 0
cdn_theme: bootstrap
cdn_cache_ttl_versions: '604800'
cdn_cache_ttl_themes: '604800'
cdn_cache_ttl_assets: '0'
cdn_cache_ttl_library: '0'
reset_http_request_cache: ''
