<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Datetime\DrupalDateTime;
use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Ajax\OpenDialogCommand;
use Drupal\Core\Ajax\CloseDialogCommand;
use Drupal\views\ViewExecutable;
use Drupal\views\Entity\View;

/**
 * Implements hook_form_commerce_product_form_alter() for node edit form.
**/
function trilliumlincoln_utility_form_commerce_product_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $product = $form_state->getFormObject()->getEntity();
  if(!empty($form['field_car_year']['widget'][0]['value'])) {
    $form['field_car_year']['widget'][0]['value']['#date_year_range'] = '-30:+0';
    $form['field_car_year']['widget'][0]['value']['#date_part_order'] = ['year'];
  }

  if(!empty($form['field_car_stock_number'])) {
    $form['field_car_stock_number']['#attributes']['class'][] = 'hidden';
  }
}

/**
 * Implements hook_theme().
 */
function trilliumlincoln_utility_theme($existing, $type, $theme, $path) {
  return [
    'redirect-lincoln' => [
      'variables' => [
        'url' => Null
      ],
    ],
  ];
}

/**
 * Implements hook_webform_submission_form_alter().
**/
function trilliumlincoln_utility_webform_submission_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  switch ($form_id) {
    case 'webform_submission_test_drive_add_form':
      honeypot_add_form_protection(
        $form,
        $form_state,
        ['honeypot', 'time_restriction']
      );

      $form['actions']['submit']['#attributes']['class'][] = 'use-ajax';
      $form['actions']['submit']['#attributes']['class'][] = 'btn';
      $form['actions']['submit']['#attributes']['class'][] = 'btn-info';
      $form['actions']['submit']['#attributes']['class'][] = 'btn-lg';

      $form['actions']['submit']['#ajax'] = [
        'callback' => 'submitModalFormAjax'
      ];
      $form['#attached']['library'][] = 'core/drupal.dialog.ajax';

      break;
  }
}

/**
 * AJAX callback handler that displays any errors or a success message.
 */
function submitModalFormAjax(array $form, FormStateInterface $form_state) {
    $response = new AjaxResponse();

    $form_object = $form_state->getFormObject();
    $webform_submission = $form_object->getEntity();
    $webform = $webform_submission->getWebform();
    $message = drupal_get_messages();

    // If there are any form errors, re-display the form.
    if ($form_state->hasAnyErrors()) {
      $response->addCommand(new OpenDialogCommand('#trilliumlincoln-close-modal', $webform->label(), $form, ['modal' => true]));
    }
    else {
      $response->addCommand(new CloseDialogCommand('#trilliumlincoln-close-modal'));
    }

    return $response;
}

function trilliumlincoln_utility_form_views_exposed_form_alter(&$form, FormStateInterface $form_state) {
  $view = $form_state->get('view');
  $display = $form_state->get('display');

  if ($display['id'] == 'page_1' && $view->id() == 'product_list') {
    $options = ["" => 'All'] + $form['field_car_type_target_id']['#options'];
    $form['field_car_type_target_id']['#options'] = $options;
    $form['field_car_type_target_id']['#prefix'] = '<div class="form-wrapper-filter">';

    $form['actions']['submit']['#attributes']['class'][] = 'btn-info';
    $form['actions']['submit']['#attributes']['class'][] = 'btn-lg';

    $query = db_select('commerce_product__field_car_year', 'fcy');
    $query->fields('fcy', ['field_car_year_value']);
    $query->condition('fcy.deleted', 0);
    $query->condition('fcy.bundle', 'car');
    $query->orderBy('fcy.field_car_year_value', 'ASC');
    $field_car_year_value = $query->execute()->fetchCol();

    $options_year = [
      '' => t('Year')
    ];

    if (!empty($field_car_year_value)) {
      foreach ($field_car_year_value as $key => $value) {
        $options_year[$value] = date('Y', strtotime($value));
      }
    }

    $form['field_car_year_value']['#type'] = 'select';
    $form['field_car_year_value']['#size'] = 1;
    $form['field_car_year_value']['#options'] = $options_year;
    
    $form['field_car_model_target_id']['#suffix'] = '</div>';
    $form['field_car_model_target_id']['#options']['All'] = t('Model');

  }
}